/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_7 (
    input [1:0] alufn_add,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] s,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [7:0] sum;
  
  reg xb;
  
  always @* begin
    
    case (alufn_add)
      2'h0: begin
        sum = a + b;
      end
      2'h1: begin
        sum = a - b;
      end
      default: begin
        sum = a - b;
      end
    endcase
    xb = b[7+0-:1] ^ alufn_add;
    z = (sum == 8'h00);
    v = (a[7+0-:1] & xb & !(sum[7+0-:1])) | (!(a[7+0-:1]) & !(xb) & sum[7+0-:1]);
    n = sum[7+0-:1];
    s = sum;
  end
endmodule
