/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_9 (
    input [3:0] alufn_boole,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] boole
  );
  
  
  
  always @* begin
    
    case (alufn_boole)
      4'h0: begin
        boole = 8'h00;
      end
      4'h8: begin
        boole = a & b;
      end
      4'he: begin
        boole = a | b;
      end
      4'h6: begin
        boole = a ^ b;
      end
      4'ha: begin
        boole = a;
      end
      default: begin
        boole = 8'h00;
      end
    endcase
  end
endmodule
