/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_21 (
    input [1:0] alufn_shift,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] shift
  );
  
  
  
  always @* begin
    shift = 8'h00;
    
    case (alufn_shift)
      2'h0: begin
        shift = a << b[0+2-:3];
      end
      2'h1: begin
        shift = a >> b[0+2-:3];
      end
      2'h2: begin
        shift = $signed(a) <<< b[0+2-:3];
      end
      2'h3: begin
        shift = $signed(a) >>> b[0+2-:3];
      end
      default: begin
        shift = 8'h00;
      end
    endcase
  end
endmodule
